<div class="conteneur_connexion left absolute" id="dialog" name="conteneur_connexion"></div> <!-- fenetre de la popup de connexion  -->

<div class="bandeau_header left">
	<?php echo $this->connexion; ?>
	<?php echo $this->deconnexion; ?>
</div>

<div class="contenu left">
	<div class="bandeau left">
		<div class="bandeau_texte texte">&Eacute;dition de votre profil</div>
	</div>
	<div class="contenu_form left">
		<?php echo $this->editForm; ?>
	</div>
</div>