<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<?php echo $this->headTitle('Forum - Social\'Insset') ?>
	<?php echo $this->headLink()->appendStylesheet($this->BaseUrl() . '/css/style.css')
								->appendStylesheet($this->BaseUrl() . '/css/reset.css') ?>

	<?php echo $this->headScript()->appendFile($this->BaseUrl() . '/js/affiche_login.js','text/javascript'); ?> 
	<?php echo $this->JQuery(); ?>
</head>
<body>
	<div class="conteneur_body">
		<div class="header">
			<?php echo $this->layout()->header; ?>
		</div>

		<div class="content">
			<?php echo $this->layout()->content; ?>
		</div>
				
		<div class="footer">
			<?php echo $this->layout()->footer; ?>	
		</div>
	</div>
</body>
</html>